version: "3.9"

services:
  backend:
    container_name: medium_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - "8787:8787"

  frontend:
    container_name: medium_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes: 
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend