version: "3.9"

services:
  backend:
    container_name: medium_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    container_name: medium_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes: 
      - ./frontend:/frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - db

  db:
    container_name: db
    restart: always
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data