name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="Your_prisma_accelerate_key"
JWT_SECRET="Your_Secret_Key"
GEMINI_API_KEY="Your_gemini_key"

[dev]
ip = "0.0.0.0"
port = 8080
local_protocol = "http"